.TH "C:/Users/muell/OneDrive/UNI/2. Semester/Informatik 2/Projekt/qt_Projekt/TempMonitor/mainwindow.cpp" 3 "Mon Jul 4 2016" "Temp Monitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/muell/OneDrive/UNI/2. Semester/Informatik 2/Projekt/qt_Projekt/TempMonitor/mainwindow.cpp \- MainWindow::on_btn_connect_clicked\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'temp\&.h'\fP
.br
\fC#include <QtCharts/QChart>\fP
.br
\fC#include <QtCharts/QLineSeries>\fP
.br
\fC#include <QtCharts/QChartView>\fP
.br
\fC#include <QtCharts/QXYSeries>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QtSerialPort/QSerialPortInfo>\fP
.br
\fC#include <QSerialPort>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QtCharts/QDateTimeAxis>\fP
.br
\fC#include <QtCharts/QValueAxis>\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <QGradient>\fP
.br
\fC#include <QLinearGradient>\fP
.br
\fC#include <QPen>\fP
.br

.SH "Detailed Description"
.PP 
MainWindow::on_btn_connect_clicked\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Temp Monitor from the source code\&.
