.TH "C:/Users/muell/OneDrive/UNI/2. Semester/Informatik 2/Projekt/qt_Projekt/TempMonitor/main.cpp" 3 "Mon Jul 4 2016" "Temp Monitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/muell/OneDrive/UNI/2. Semester/Informatik 2/Projekt/qt_Projekt/TempMonitor/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QApplication>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Temp Monitor from the source code\&.
