.TH "md__c_1__users_muell__one_drive__u_n_i_2.__semester__informatik_2__projekt_qt__projekt__temp_monitor__r_e_a_d_m_e" 3 "Tue Jul 5 2016" "Temp Monitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users_muell__one_drive__u_n_i_2.__semester__informatik_2__projekt_qt__projekt__temp_monitor__r_e_a_d_m_e \- TempMonitor 
A Project to measure the temperature with an arduino which sends it via usb to a computer\&. On your machine you run the TempMonitor programm for receiving the data and displaying it as a chart\&. 
