.TH "C:/Users/muell/OneDrive/UNI/2. Semester/Informatik 2/Projekt/qt_Projekt/TempMonitor/README.md" 3 "Mon Jul 4 2016" "Temp Monitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/muell/OneDrive/UNI/2. Semester/Informatik 2/Projekt/qt_Projekt/TempMonitor/README.md \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Temp Monitor from the source code\&.
