.TH "Serial" 3 "Mon Jul 4 2016" "Temp Monitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serial \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBopen\fP (QString portName)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Temp Monitor from the source code\&.
