.TH "Temp" 3 "Tue Jul 5 2016" "Temp Monitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Temp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <temp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTemp\fP (double temperature, QDateTime time, int interval)"
.br
.RI "\fIcreate a new \fBTemp\fP object for storing the temperature and time \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtemp\fP"
.br
.ti -1c
.RI "QDateTime \fBtimestamp\fP"
.br
.ti -1c
.RI "int \fBinterval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class for storing a dataset of a temperature value and a timestamp 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Temp::Temp (double temperature, QDateTime time, int interval)"

.PP
create a new \fBTemp\fP object for storing the temperature and time 
.PP
\fBParameters:\fP
.RS 4
\fItemperature\fP stores as a double\&. No unit is assoziated, but °C is used 
.br
\fItime\fP as QDateTime object 
.br
\fIinterval\fP of measuring the tempearture in seconds 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Temp Monitor from the source code\&.
